
    document.write("<h3>Question1</h3>");
    var username;
    document.write("<h3>Question2</h3>");
    var myName="Muhammad Haseeb";
    document.write("<h3>Question3</h3>");
    var message;
    message="Hello World";
    alert(message);
    document.write("<h3>Question4</h3>");
    var name="Haseeb";
    var age="20";
    var certification="Web and Mobile Hybrid app development";
    alert(name);
    alert(age+" years old");
    alert(certification);
    document.write("<h3>Question5</h3>");
    word="PIZZA";
    alert(word+"\n"+word.substring(0,4)+"\n"+word.substring(0,3)+"\n"+word.substring(0,2)+"\n"+word.substring(0,1));
    document.write("<h3>Question6</h3>");
    var email="m.haseeb5678@gmail.com";
    alert("My email address is "+email);
    document.write("<h3>Question7</h3>");
    var book="A smarter way to learn JavaScript";
    alert("book");
    document.write("<h3>Question8</h3>");
    document.write("Yah! I can write HTML content Through JavaScript");
    document.write("<h3>Question9</h3>");
    var strng= "▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬";
    alert(strng);
    document.write(strng);