document.write("<h3>Question1</h3>");
num1=4;
num2=7;
sum=num1+num2;
document.write("Sum of "+num1+" and "+num2+" is "+sum);
document.write("<h3>Question2</h3>");
num1=4;
num2=7;
sub=num1-num2;
document.write("Subtraction of "+num1+" and "+num2+" is "+sub+"<br>");
mul=num1*num2;
document.write("Multiplication of "+num1+" and "+num2+" is "+mul+"<br>");
div=num1/num2;
document.write("Division of "+num1+" and "+num2+" is "+div+"<br>");
mod=num1%num2;
document.write("Modulus of "+num1+" and "+num2+" is "+mod+"<br>");
document.write("<h3>Question3</h3>");
var num;
document.write("Value after varialbe declaration is: "+num+"<br>");
num=20;
document.write("Initial Value: "+num+"<br>");
num=num+1;
document.write("Value after increment is: "+num+"<br>");
num=num+7;
document.write("Value after addition is: "+num+"<br>");
num=num-1;
document.write("Value after decrement is: "+num+"<br>");
num=num/3;
document.write("The remainder is: "+num);
document.write("<h3>Question4</h3>");
var ticketCost=600;
numberOfTickets=5;
fiveTicketsCost=ticketCost*numberOfTickets;
document.write("Total cost to buy "+numberOfTickets+" tickets to a movie is "+fiveTicketsCost+"PKR");
document.write("<h3>Question5</h3>");
table=7;
document.write("Table of "+table);
document.write("<br>"+table+" x 1 = "+table*1+"<br>"+table+" x 2 = "+table*2+"<br>"+table+" x 3 = "+table*3+"<br>"+table+" x 4 = "+table*4+"<br>"+table+" x 5 = "+table*5+"<br>"+table+" x 6 = "+table*6+"<br>"+table+" x 7 = "+table*7+"<br>"+table+" x 8 = "+table*8+"<br>"+table+" x 9 = "+table*9+"<br>"+table+" x 10 = "+table*10);
document.write("<h3>Question6</h3>");
var celsiusTemp=30;
var fahrenheit=(celsiusTemp*9/5)+32;
document.write(celsiusTemp+"C is "+fahrenheit+"F");
var ftemp=70;
var ctemp=(ftemp-32)*5/9;
document.write("<br>"+ftemp+"F is "+ctemp+"C");
document.write("<h3>Question7</h3>");
var item1price=800,item2price=600,item1quantity=2,item2quantity=4,shippingCharges=300;
document.write("Price of item 1 is "+item1price+"<br>Quantity of item 1 is "+item1quantity+"<br>Price of item 2 is "+item2price+"<br>Quantity of item 2 is "+item2quantity+"<br>Shipping Charges"+shippingCharges+"<br>");
Tcost=(item1price*item1quantity)+(item2price*item2quantity)+shippingCharges;
document.write("<br>Total cost of yout order is "+Tcost);
document.write("<h3>Question8</h3>");
var tMarks=1100;
var oMarks=989;
percentage=oMarks/tMarks*100;
document.write("Total Marks: "+tMarks+"<br>Marks obtained: "+oMarks+"<br>Percentage: "+percentage+"%");
document.write("<h3>Question9</h3>");
var USDollars=10,SaudiRiyals=25,dollarExchangeRate=104.80,riyalExchangeRate=28;
totalinPKR=(USDollars*dollarExchangeRate)+(SaudiRiyals*riyalExchangeRate);
document.write("Total Currency in PKR: "+totalinPKR);
document.write("<h3>Question10</h3>");
var anyNum=9;
calculations=((anyNum+5)*10)/2;
document.write(calculations);
document.write("<h3>Question11</h3>");
var CurrentYear=2020,BirthYear=2000;
age1=CurrentYear-BirthYear;
age2=age1-1;
document.write("Current Year: "+CurrentYear+"<br>Birth Year: "+BirthYear+"<br>2 Possible ages: "+age1+", "+age2);
document.write("<h3>Question12</h3>");
var radius=30;
var circumference=2*3.142*30;
var area=3.142*radius*radius;
document.write("Radius of a circle: "+radius+"<br>The circumference is: "+circumference+"<br>The area is: "+area);
document.write("<h3>Question13</h3>");
favSnack="Lays";
currAge=20;
maxAge=70;
amountPerDay=2;
totalEat=((maxAge-currAge)*365)*amountPerDay;
document.write("You will need "+totalEat+" to last you until the ripe old age of "+maxAge);